
# Using Ubuntu 14.04 (trusty, sudo-enabled
# https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
# Using latest mono dependency
# https://docs.travis-ci.com/user/languages/csharp/#Mono
# Installing dependencies on Ubuntu for Unreal Engine
# https://wiki.unrealengine.com/Building_On_Linux#Setting_up_on_Ubuntu
# API Token setup
# https://docs.travis-ci.com/user/private-dependencies/#API-Token

language: generic
os: linux
sudo: required
dist: trusty
mono: latest
#addons:
#    apt:
#      update: true
before_install:
- chmod a+x ./install.sh
- sudo apt-get install build-essential mono-gmcs mono-xbuild mono-dmcs libmono-corlib4.0-cil libmono-system-data-datasetextensions4.0-cil libmono-system-web-extensions4.0-cil libmono-system-management4.0-cil libmono-system-xml-linq4.0-cil cmake dos2unix clang-3.5 libfreetype6-dev libgtk-3-dev libmono-microsoft-build-tasks-v4.0-4.0-cil xdg-user-dirs
- echo -e "machine github.com\n  login $GITHUB_OAUTH_TOKEN" >> ~/.netrc
install:
- ./install.sh
#before_script:
#- chmod a+x ./build.sh
#script:
#- ./build.sh
before_script:
- chmod a+x ./prepare.sh
- chmod a+x ./compile.sh
- chmod a+x ./build.sh
- chmod a+x ./cook.sh
- chmod a+x ./archive.sh
script:
- ./prepare.sh
- ./compile.sh
- ./build.sh
- ./cook.sh
- ./archive.sh
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$(pwd)/Release/TestUnityCI.zip"
  skip_cleanup: true
  on:
    tags: true