language: generic
os: linux
rvm:
- 2.2
before_install:
- chmod a+x ./install.sh
install:
- ./install.sh
#before_script:
#- chmod a+x ./build.sh
#script:
#- ./build.sh
before_script:
- chmod a+x ./prepare.sh
- chmod a+x ./compile.sh
- chmod a+x ./build.sh
- chmod a+x ./cook.sh
- chmod a+x ./archive.sh
script:
- ./prepare.sh
- ./compile.sh
- ./build.sh
- ./cook.sh
- ./archive.sh
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$(pwd)/Release/TestUnityCI.zip"
  skip_cleanup: true
  on:
    tags: true